[package]
name = "project-corrosion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.14.1"
midir = "0.9.1"
egui = "0.21.0"
clap-sys = "0.3.0"
libloading = "0.7.4"
